// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID          int32         `json:"id"`
	UserID      sql.NullInt32 `json:"user_id"`
	Amount      string        `json:"amount"`
	Description string        `json:"description"`
	Category    string        `json:"category"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type Profile struct {
	ID             int32         `json:"id"`
	UserID         sql.NullInt32 `json:"user_id"`
	Bio            string        `json:"bio"`
	Name           string        `json:"name"`
	ProfilePicture string        `json:"profile_picture"`
	CreatedAt      sql.NullTime  `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type Report struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Title     string        `json:"title"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type Setting struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Theme     sql.NullString `json:"theme"`
	Currency  sql.NullString `json:"currency"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
