@startuml UpdateUser
title Update User API Workflow

actor Client
participant "User Authentication\nService" as Service
participant "User Store" as Store

Client -> Service : Send UpdateUser request
Service -> Service : Validate request
alt Invalid request
    Service -> Client : Return INVALID_REQUEST error
else Valid request
    alt ListUserByEmail error
        Store -> Service : Return INTERNAL_ERROR error
    else ListUserByEmail success
        Store -> Service : Return User
        alt Username does not exist
            Store -> Service : Return USER_NOT_FOUND error
        else Username exists
            alt New Username is provided
                Service -> Store : ModifyUserUsername
                alt ModifyUserUsername error
                    Store -> Service : Return INTERNAL_ERROR error
                end
            end
            alt New Password is provided
                alt New Password is valid
                    Service -> Service : CompareHashAndPassword
                    alt New Password same as old password
                        Service -> Client : Return INTERNAL_ERROR error
                    else New Password not same as old password
                        alt Password length less than 8
                            Service -> Client : Return INVALID_PASSWORD error
                        else Password length greater than 8
                            Service -> Service : GenerateFromPassword
                            alt GenerateFromPassword error
                                Service -> Client : Return INTERNAL_ERROR error
                            else GenerateFromPassword success
                                Service -> Store : ModifyUserPassword
                                alt ModifyUserPassword error
                                    Store -> Service : Return INTERNAL_ERROR error
                                else ModifyUserPassword success
                                    Service -> Client : Return USER_MODIFIED_SUCCESSFULLY
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end
@enduml