@startuml DeleteUser
title Delete User API Workflow

actor Client
participant "User Authentication\nService" as Service
participant "User Store" as Store

Client -> Service : Send DeleteUser request
Service -> Store : ListUserByUsername
Service -> Service : Validate request
alt Invalid request
    Service -> Client : Return INVALID_REQUEST error
else Valid request
    alt ListUserByUsername error
        Store -> Service : Return INTERNAL_ERROR error
    else ListUserByUsername success
        Store -> Service : Return User
        alt Username does not exist
            Store -> Service : Return USER_NOT_FOUND error
        else Username exists
            Service -> Store : DeleteUser
            alt DeleteUser error
                Store -> Service : Return INTERNAL_ERROR error
            else DeleteUser success
                Store -> Service : Return Deleted User
        end
    end
end

@enduml